### ISSUE TITLE
example fails to run 

### ISSUE THREAD

**Issue by nrfm** [RickMoynihan/lein-tools-deps#81]
check out the project, cd into example, upgrade `:plugins [[lein-tools-deps "0.4.2-SNAPSHOT"]]` to `:plugins [[lein-tools-deps "0.4.3"]]` as `0.4.2-SNAPSHOT` is not found in clojars.

as per readme do `lein repl`.

I get 
```
$ lein repl
If there are a lot of uncached dependencies this might take a while ...
java.lang.NullPointerException: null
 at clojure.tools.deps.alpha.util.maven$make_session.invokeStatic (maven.clj:141)
    clojure.tools.deps.alpha.util.maven$make_session.invoke (maven.clj:138)
    clojure.tools.deps.alpha.extensions.maven$eval1004$fn__1006.invoke (maven.clj:78)
    clojure.lang.MultiFn.invoke (MultiFn.java:243)
    clojure.tools.deps.alpha$expand_deps.invokeStatic (alpha.clj:187)
    clojure.tools.deps.alpha$expand_deps.invoke (alpha.clj:168)
    clojure.tools.deps.alpha$resolve_deps.invokeStatic (alpha.clj:234)
    clojure.tools.deps.alpha$resolve_deps.invoke (alpha.clj:216)
    clojure.lang.AFn.applyToHelper (AFn.java:156)
    clojure.lang.AFn.applyTo (AFn.java:144)
    clojure.core$apply.invokeStatic (core.clj:646)
    clojure.core$memoize$fn__5708.doInvoke (core.clj:6107)
    clojure.lang.RestFn.invoke (RestFn.java:421)
    lein_tools_deps.lein_project$resolve_deps.invokeStatic (lein_project.clj:54)
    lein_tools_deps.lein_project$resolve_deps.invoke (lein_project.clj:50)
    lein_tools_deps.plugin$apply_middleware.invokeStatic (plugin.clj:22)
    lein_tools_deps.plugin$apply_middleware.invoke (plugin.clj:17)
    lein_tools_deps.plugin$apply_middleware.invokeStatic (plugin.clj:25)
    lein_tools_deps.plugin$apply_middleware.invoke (plugin.clj:17)
    lein_tools_deps.plugin$resolve_dependencies_with_deps_edn.invokeStatic (plugin.clj:47)
    lein_tools_deps.plugin$resolve_dependencies_with_deps_edn.invoke (plugin.clj:34)
    clojure.lang.Var.invoke (Var.java:379)
    leiningen.core.project$apply_middleware.invokeStatic (project.clj:750)
    leiningen.core.project$apply_middleware.invoke (project.clj:743)
    clojure.lang.ArrayChunk.reduce (ArrayChunk.java:58)
    clojure.core.protocols$fn__6750.invokeStatic (protocols.clj:136)
    clojure.core.protocols/fn (protocols.clj:124)
    clojure.core.protocols$fn__6710$G__6705__6719.invoke (protocols.clj:19)
    clojure.core.protocols$seq_reduce.invokeStatic (protocols.clj:31)
    clojure.core.protocols$fn__6738.invokeStatic (protocols.clj:75)
    clojure.core.protocols/fn (protocols.clj:75)
    clojure.core.protocols$fn__6684$G__6679__6697.invoke (protocols.clj:13)
    clojure.core$reduce.invokeStatic (core.clj:6545)
    clojure.core$reduce.invoke (core.clj:6527)
    leiningen.core.project$apply_middleware.invokeStatic (project.clj:745)
    leiningen.core.project$apply_middleware.invoke (project.clj:743)
    leiningen.core.project$activate_middleware.invokeStatic (project.clj:777)
    leiningen.core.project$activate_middleware.invoke (project.clj:773)
    leiningen.core.project$init_project.invokeStatic (project.clj:902)
    leiningen.core.project$init_project.invoke (project.clj:892)
    leiningen.core.project$read.invokeStatic (project.clj:973)
    leiningen.core.project$read.invoke (project.clj:970)
    leiningen.core.project$read.invokeStatic (project.clj:974)
    leiningen.core.project$read.invoke (project.clj:970)
    leiningen.core.main$_main$fn__5998.invoke (main.clj:397)
    leiningen.core.main$_main.invokeStatic (main.clj:394)
    leiningen.core.main$_main.doInvoke (main.clj:391)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.lang.Var.invoke (Var.java:379)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invokeStatic (core.clj:646)
    clojure.main$main_opt.invokeStatic (main.clj:314)
    clojure.main$main_opt.invoke (main.clj:310)
    clojure.main$main.invokeStatic (main.clj:421)
    clojure.main$main.doInvoke (main.clj:384)
    clojure.lang.RestFn.invoke (RestFn.java:436)
    clojure.lang.Var.invoke (Var.java:388)
    clojure.lang.AFn.applyToHelper (AFn.java:160)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.main.main (main.java:37)
```
osx
clojure version
```
$ brew info clojure
clojure: stable 1.10.0.411
```

**Comment by RickMoynihan** [comment]
Fixed.  Thanks.

**Comment by nrfm** [comment]
still getting the sam error.

1. clone project
2. `cd example`
3. `lein repl`

results in 
```
$ cd example/
$ ls
README.md       criterium       deps.edn        local-root      project.clj     src             test
$ lein repl
If there are a lot of uncached dependencies this might take a while ...
java.lang.NullPointerException: null
 at clojure.tools.deps.alpha.util.maven$make_session.invokeStatic (maven.clj:141)
    clojure.tools.deps.alpha.util.maven$make_session.invoke (maven.clj:138)
    clojure.tools.deps.alpha.extensions.maven$eval1004$fn__1006.invoke (maven.clj:78)
    clojure.lang.MultiFn.invoke (MultiFn.java:243)
    clojure.tools.deps.alpha$expand_deps.invokeStatic (alpha.clj:187)
    clojure.tools.deps.alpha$expand_deps.invoke (alpha.clj:168)
    clojure.tools.deps.alpha$resolve_deps.invokeStatic (alpha.clj:234)
    clojure.tools.deps.alpha$resolve_deps.invoke (alpha.clj:216)
    clojure.lang.AFn.applyToHelper (AFn.java:156)
    clojure.lang.AFn.applyTo (AFn.java:144)
    clojure.core$apply.invokeStatic (core.clj:646)
    clojure.core$memoize$fn__5708.doInvoke (core.clj:6107)
    clojure.lang.RestFn.invoke (RestFn.java:421)
    lein_tools_deps.lein_project$resolve_deps.invokeStatic (lein_project.clj:54)
    lein_tools_deps.lein_project$resolve_deps.invoke (lein_project.clj:50)
    lein_tools_deps.plugin$apply_middleware.invokeStatic (plugin.clj:22)
    lein_tools_deps.plugin$apply_middleware.invoke (plugin.clj:17)
    lein_tools_deps.plugin$apply_middleware.invokeStatic (plugin.clj:25)
    lein_tools_deps.plugin$apply_middleware.invoke (plugin.clj:17)
    lein_tools_deps.plugin$resolve_dependencies_with_deps_edn.invokeStatic (plugin.clj:47)
    lein_tools_deps.plugin$resolve_dependencies_with_deps_edn.invoke (plugin.clj:34)
    clojure.lang.Var.invoke (Var.java:379)
    leiningen.core.project$apply_middleware.invokeStatic (project.clj:750)
    leiningen.core.project$apply_middleware.invoke (project.clj:743)
    clojure.lang.ArrayChunk.reduce (ArrayChunk.java:58)
    clojure.core.protocols$fn__6750.invokeStatic (protocols.clj:136)
    clojure.core.protocols/fn (protocols.clj:124)
    clojure.core.protocols$fn__6710$G__6705__6719.invoke (protocols.clj:19)
    clojure.core.protocols$seq_reduce.invokeStatic (protocols.clj:31)
    clojure.core.protocols$fn__6738.invokeStatic (protocols.clj:75)
    clojure.core.protocols/fn (protocols.clj:75)
    clojure.core.protocols$fn__6684$G__6679__6697.invoke (protocols.clj:13)
    clojure.core$reduce.invokeStatic (core.clj:6545)
    clojure.core$reduce.invoke (core.clj:6527)
    leiningen.core.project$apply_middleware.invokeStatic (project.clj:745)
    leiningen.core.project$apply_middleware.invoke (project.clj:743)
    leiningen.core.project$activate_middleware.invokeStatic (project.clj:777)
    leiningen.core.project$activate_middleware.invoke (project.clj:773)
    leiningen.core.project$init_project.invokeStatic (project.clj:902)
    leiningen.core.project$init_project.invoke (project.clj:892)
    leiningen.core.project$read.invokeStatic (project.clj:973)
    leiningen.core.project$read.invoke (project.clj:970)
    leiningen.core.project$read.invokeStatic (project.clj:974)
    leiningen.core.project$read.invoke (project.clj:970)
    leiningen.core.main$_main$fn__5998.invoke (main.clj:397)
    leiningen.core.main$_main.invokeStatic (main.clj:394)
    leiningen.core.main$_main.doInvoke (main.clj:391)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.lang.Var.invoke (Var.java:379)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invokeStatic (core.clj:646)
    clojure.main$main_opt.invokeStatic (main.clj:314)
    clojure.main$main_opt.invoke (main.clj:310)
    clojure.main$main.invokeStatic (main.clj:421)
    clojure.main$main.doInvoke (main.clj:384)
    clojure.lang.RestFn.invoke (RestFn.java:436)
    clojure.lang.Var.invoke (Var.java:388)
    clojure.lang.AFn.applyToHelper (AFn.java:160)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.main.main (main.java:37)
```

**Comment by nrfm** [comment]
Thanks, that solved it. 
i was on `2.7.1` and after upgrading to `2.8.3` it worked.

Apologies for the noise, i totally missed that in the readme.
